name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  burn-central-client:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: burn-central-client
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
